<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WacomRealController</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Backup\**" />
    <EmbeddedResource Remove="Backup\**" />
    <None Remove="Backup\**" />
  </ItemGroup>

  <Target Name="CopyExecutableToRoot" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)WacomRealController.exe" DestinationFolder="$(MSBuildProjectDirectory)" />
  </Target>

  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
</Project>
